spring.application.name=goldenlibrary-api

# CONFIGURACAO DO MONGO DB
spring.data.mongodb.uri=mongodb+srv://kayufernandez1910_db_user:SYntS8j6EYOIRZIB@cluster0.1pifhsk.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=goldenlibrary
# JWT TOKEN
api.security.token.secret=bXktc3VwZXItc2VjcmV0LWtleS13aGljaC1pcy12ZXJ5LWxvbmc=